// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUJTmoI0mmzJYjfRk2Y5RcBahdpLviH18',
    appId: '1:465413742599:web:83932d52987968ffb54aa2',
    messagingSenderId: '465413742599',
    projectId: 'appnexts',
    authDomain: 'appnexts.firebaseapp.com',
    storageBucket: 'appnexts.firebasestorage.app',
    measurementId: 'G-MKLENJ7NL9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQZVTMIgag1V2vhnWAvkddX6u0pSyMp6M',
    appId: '1:465413742599:android:474c9222e1cf3a67b54aa2',
    messagingSenderId: '465413742599',
    projectId: 'appnexts',
    storageBucket: 'appnexts.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAY1BpnqV4UuvXavrT_dua3922VuRPIqUg',
    appId: '1:465413742599:ios:236f6236320470bdb54aa2',
    messagingSenderId: '465413742599',
    projectId: 'appnexts',
    storageBucket: 'appnexts.firebasestorage.app',
    iosBundleId: 'com.example.newProject1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAY1BpnqV4UuvXavrT_dua3922VuRPIqUg',
    appId: '1:465413742599:ios:236f6236320470bdb54aa2',
    messagingSenderId: '465413742599',
    projectId: 'appnexts',
    storageBucket: 'appnexts.firebasestorage.app',
    iosBundleId: 'com.example.newProject1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUJTmoI0mmzJYjfRk2Y5RcBahdpLviH18',
    appId: '1:465413742599:web:a14aed10057e59fcb54aa2',
    messagingSenderId: '465413742599',
    projectId: 'appnexts',
    authDomain: 'appnexts.firebaseapp.com',
    storageBucket: 'appnexts.firebasestorage.app',
    measurementId: 'G-12THFLJYFD',
  );

}